//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopManageProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Orders
    {
        
        public Orders()
        {
            this.OrderDetail = new HashSet<OrderDetail>();
        }
    
        public long OrderId { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<long> UserId { get; set; }
        //[Required]
        public string ShipName { get; set; }
        //[Required]
        [Phone]
        public string ShipMobile { get; set; }
       // [Required]
        public string ShipAddress { get; set; }
        //[Required]
        [EmailAddress]
        public string ShipEmail { get; set; }
        public Nullable<bool> Status { get; set; }
    
       
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
        public virtual Users Users { get; set; }
    }
}
