//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopManageProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetail = new HashSet<OrderDetail>();
        }
    
        public long ProductId { get; set; }
        [Required]
        [MaxLength(250),MinLength(1)]
        public string Name { get; set; }
        [Required]
        [MaxLength(10), MinLength(1)]
        public string Code { get; set; }
        [Required]
        [MaxLength(500), MinLength(1)]
        public string Description { get; set; }
        [Required]
        [MaxLength(250), MinLength(1)]
        public string Image { get; set; }
        [Required]
        [MaxLength(18), MinLength(1)]
        [DisplayFormat( DataFormatString = "{0:0,0đ}")]
        public Nullable<decimal> Price { get; set; }
        [Required]
        [MaxLength(18), MinLength(1)]
        [DisplayFormat( DataFormatString = "{0:0,0đ}")]
        public Nullable<decimal> PromotionPrice { get; set; }
        [Required]
        public Nullable<int> Quanlity { get; set; }

        public Nullable<long> ProductCategoryId { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
    }
}
