//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopManageProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UsersLogin
    {
       [Required(ErrorMessage ="Bạn phải nhập tài khoản")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Bạn phải nhập mật khẩu")]
        public string Password { get; set; }
    }

    public partial class Users
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public long UserId { get; set; }

        [Required(ErrorMessage = "Bạn phải nhập tên tài khoản.")]
        [StringLength(50, MinimumLength = 5)]
        public string UserName { get; set; }

        [Required(ErrorMessage = "Bạn phải nhập mật khẩu.")]
        [StringLength(30, MinimumLength = 5)]
        public string Password { get; set; }

        [Required(ErrorMessage = "Bạn phải nhập mật khẩu.")]
        [StringLength(30, MinimumLength = 5)]
        [Compare("Password", ErrorMessage = "Mật khẩu nhập lại không đúng.")]
        public string ConfirmPassword { get; set; }

        public string GroupId { get; set; }
        [Required(ErrorMessage = "Bạn phải nhập tên.")]
        [StringLength(50, MinimumLength = 5)]
        public string Name { get; set; }
        [Required(ErrorMessage = "Bạn phải nhập địa chỉ.")]
        [StringLength(50, MinimumLength = 5)]
        public string Address { get; set; }
        [Required(ErrorMessage = "Bạn phải nhập email.")]
        [StringLength(50, MinimumLength = 5)]
        [EmailAddress]
        public string Email { get; set; }
        [Phone]
        [StringLength(30, MinimumLength = 5)]
        [Required(ErrorMessage = "Bạn phải nhập số điện thoại.")]
        public string Phone { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public bool Status { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual UserGroup UserGroup { get; set; }
    }
}
